EndPoint.Site/Areas/Admin/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EndPoint.Site.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

 
    }
}

EndPoint.Site/Controllers/HomeController.cs
using Application;
using EndPoint.Site.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace EndPoint.Site.Controllers
{
    public class HomeController : Controller
    {
        private UnitOfWork _context;

        public HomeController()
        {
            _context = new UnitOfWork();
        }

        public IActionResult Index()
        {
            ViewBag.groups = _context.PageGroup.getAll();


            var pages = _context.Page.GetTop();

            ViewBag.pages = pages.Select(s => new PageViewModel
            {
                id = s.PageId,
                PageTitle = s.PageTitle,
                ShortDescription = s.ShortDescription,
                Image = s.Image,
                CreateDate = s.CreateDate
            });
            return View();


        }
        public IActionResult Indexss()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

EndPoint.Site/ViewComponents/LastNewsViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Application;
using EndPoint.Site.Models;
using Microsoft.AspNetCore.Mvc;

namespace EndPoint.Site.ViewComponents
{
    public class LastNewsViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {

            UnitOfWork db = new UnitOfWork();
            var pageGroups = db.Page.getAll("", s => s.PageTitle != null, s => s.OrderByDescending(q => q.CreateDate)).Take(5);

            var q = pageGroups.Select(s => new PageViewModel
            {
                id = s.PageId,
                PageTitle = s.PageTitle,
                ShortDescription = s.ShortDescription,
                Image = s.Image,
                CreateDate  =s.CreateDate
            });

            return View(q);

        }
    }
}

EndPoint.Site/Views/Home/Index.cshtml
   <!-- slider -->
<div class="news-slider border-radius">
    <div id="slider-one" class="owl-carousel">
        <!-- each item -->
        @{

            foreach (var i in ViewBag.pages)
            {
                <div class="item">
                    <img src="@i.Image">
                    <div class="left-side">
                        <h2> <a href="~/Page/GetPage/@i.id">@i.PageTitle</a> </h2>
                        <p>
                            @i.ShortDescription
                        </p>
                        <span> <i class="fa fa-calendar"></i> انتشار : @i.CreateDate</span>
                    </div>
                    <div class="clearfix"></div>
                </div>
            }
        }

        <!-- end each item -->
        >
    </div>
    <a href="" class="news-archive"> <i class="icons icon-doc-1"></i> آرشیو کامل خبرها </a>
</div>
<!-- End slider -->
<!-- last news -->
@await Component.InvokeAsync("LastNews")
<!-- End last news -->