EndPoint.Site/Areas/Admin/Controllers/AddingController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Domain.News;
using Application;
using EndPoint.Site.Areas.Admin.Models;
using Microsoft.AspNetCore.Hosting;
using EndPoint.Site.Extention;

namespace EndPoint.Site.Areas.Admin.Controllers
{
    [Area("Admin2")]
    public class AddingController : Controller
    {
        private UnitOfWork _context;
        private readonly IWebHostEnvironment _webHostEnvironment;


        public AddingController(IWebHostEnvironment hostEnvironment)
        {
            _context = new UnitOfWork();
            _webHostEnvironment = hostEnvironment;

        }

        public IActionResult CreatePageGroup()
        {
            ViewBag.groups = _context.PageGroup.getAll();

            return View();
        }
        [HttpPost]
        public IActionResult CreatePageGroup(string GroupTitle)
        {
            PageGroup pg = new PageGroup { GroupTitle = GroupTitle };
            _context.PageGroup.insert(pg);
            _context.PageGroup.save();

            ViewBag.groups = _context.PageGroup.getAll();


            return View();
        }

        public IActionResult CreatePage()
        {
            ViewBag.groups = _context.PageGroup.getAll();
            var p = new PageModelView();
            return View(p);
        }
        [HttpPost]
        public IActionResult CreatePage(PageModelView page)
        {
            DateTime dateTime = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc);
            Page p = new Page
            {
                PageGroupId = _context.PageGroup.findByName(page.PageGroup),
                PageTitle = page.PageTitle,
                Text = page.Text,
                Visit = 0,
                ShortDescription = page.ShortDescription,
                Tags = page.Tags,
                //CreateDate = dateTime.AddSeconds(page.CreateDate).ToLocalTime(),
                Image = page.Image.SaveImage(_webHostEnvironment.WebRootPath, "\\News\\")
            };

            ;

            _context.Page.insert(p);
            _context.Page.save();

            ViewBag.groups = _context.PageGroup.getAll();

            return View();
        }
        [HttpGet]
        public IActionResult ShowPages()
        {
            var pages = _context.Page.getAll("PageGroup").Select(s => new PageModelView
            {
                id = s.PageId,
                Image2 = s.Image,
                PageTitle = s.PageTitle,
                ShortDescription = s.ShortDescription,
                PageGroup = s.PageGroup.GroupTitle
            });
            ViewBag.groups = _context.PageGroup.getAll();
            return View(pages);
        }
        [HttpGet]
        public IActionResult EditePage(int id)
        {
            DateTime origin = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc);
            TimeSpan diff = DateTime.Now - origin;

            ViewBag.groups = _context.PageGroup.getAll();
            var p = _context.Page.getByID(id);
            var page = new PageModelView
            {
                id = p.PageId,
                PageTitle = p.PageTitle,
                PageGroup = p.PageGroup.GroupTitle,
                Text = p.Text,
                Tags = p.Tags,
                Image2 = p.Image,
                ShortDescription = p.ShortDescription,
                //CreateDate2 = p.CreateDate,
                //CreateDate = Math.Floor(diff.TotalSeconds)
            };
            return View("EditePage", page);


            //return PartialView("~/Areas/Admin/Views/Adding/Components/EditePage/Default.cshtml");
        }
        [HttpPost]
        public IActionResult EditePage(PageModelView p)
        {
            string img;
            DateTime dateTime = new DateTime(1970, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc);


            if (p.Image == null)
            {
                img = p.Image2;
            }
            else
            {
                img = p.Image.SaveImage(_webHostEnvironment.WebRootPath, "\\News\\");
            }

            var page = _context.Page.getByID(p.id);

            //var page = new Page
            //{
            //    PageGroupId = _context.PageGroup.findByName(p.PageGroup),
            //    PageId = p.id,
            //    ShortDescription = p.ShortDescription,
            //    Text = p.Text,
            //    Image = img,
            //    PageTitle = p.PageTitle,
            //    Tags = p.Tags
            //};

            page.PageGroupId = _context.PageGroup.findByName(p.PageGroup);
            page.ShortDescription = p.ShortDescription;
            page.Text = p.Text;
            page.Image = img;
            page.PageTitle = p.PageTitle;
            page.Tags = p.Tags;
            //page.CreateDate = dateTime.AddSeconds(p.CreateDate).ToLocalTime();

            _context.Page.update(page);
            _context.Page.save();

            return RedirectToAction("ShowPages");
        }
    }
}

EndPoint.Site/Areas/Admin/ViewComponents/EditePageViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Application;
using EndPoint.Site.Areas.Admin.Models;
using EndPoint.Site.Models;
using Microsoft.AspNetCore.Mvc;

namespace EndPoint.Site.Areas.Admin.ViewComponents
{
    public class EditePageViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {

            UnitOfWork db = new UnitOfWork();

            var p = new PageModelView();

            return View(p);

        }
    }
}

EndPoint.Site/Areas/Admin/Views/Adding/CreatePage.cshtml
@model EndPoint.Site.Areas.Admin.Models.PageModelView
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    ViewData["Title"] = "CreatePage";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

@section Csss{
    <link rel="stylesheet" href="~/AdminPage/bower_components/select2/dist/css/select2.min.css">
    <!-- babakhani datepicker -->
    <link rel="stylesheet" href="~/AdminPage/dist/css/persian-datepicker-0.4.5.min.css" />

}


<div class="box box-primary">
    <div class="box-header with-border">
        <h3 class="box-title">مثال ساده</h3>
    </div>
    <!-- /.box-header -->
    <!-- form start -->
    <form role="form" enctype="multipart/form-data" asp-action="CreatePage" asp-controller="Adding" method="post">
        <div class="box-body">


            <div class="form-group">
                <label>معمولی</label>
                <select class="form-control select2" asp-for="PageGroup" name="PageGroup" style="width: 100%;">
                    @{
                        int s = 0;
                        foreach (var i in ViewBag.groups)
                        {
                            if (s == 0)
                            {
                                <option selected="selected">@i.GroupTitle</option>
                            }
                            else
                            {
                                <option>@i.GroupTitle</option>

                            }
                            s++;
                        }

                    }
                </select>
            </div>

            <div class="form-group">
                <label>انتخاب تاریخ شمسی با خروجی تایم استمپ </label>
                <div class="input-group date">
                    <div class="input-group-addon">
                        <i class="fa fa-calendar"></i>
                    </div>
                    <input type="text" id="tarikh" class="form-control pull-right">
                    <input type="text" asp-for="CreateDate" name="CreateDate" id="tarikhAlt" class="form-control pull-right hidden" >
                </div>
                <!-- /.input group -->
                <br>
            </div>

            <div class="form-group  ">
                <label for="exampleInputEmail1">عنوان</label>
                <input type="text" asp-for="PageTitle" name="PageTitle" class="form-control" id="PageTitle" placeholder="عنوان">
            </div>

            <div class="form-group ">
                <label>توضیح کوتاه</label>
                <textarea class="form-control" asp-for="ShortDescription" id="ShortDescription" name="ShortDescription" rows="3" placeholder="توضیح کوتاه"></textarea>
            </div>


            <div class="form-group">
                @*<textarea class="form-control" name="Text" rows="3" placeholder="متن"></textarea>*@
                <textarea id="my-textarea" asp-for="Text" name="Text"></textarea>
            </div>

            <div class="form-group">
                <label for="exampleInputFile">ارسال فایل</label>
                @{
                    if (Model.Image2 != null)
                    {
                        <img src="@Model.Image2" alt="Alternate Text" />
                    }
                }
                <input type="file" name="Image" id="exampleInputFile">

                <p class="help-block">متن راهنما</p>
            </div>

            <div class="form-group">
                <label for="exampleInputFile">کلمات کلیدی</label>
                <input type="text" asp-for="Tags" name="Tags" class="form-control" id="exampleInputEmail1" placeholder="کلمات کلیدی">
            </div>


            <div class="checkbox">
                <label>
                    <input type="checkbox"> مرا به خاطر بسپار
                </label>
            </div>
        </div>
        <!-- /.box-body -->

        <div class="box-footer">
            <button type="submit" class="btn btn-primary">ارسال</button>
        </div>
    </form>
</div>




@section Scripts{


    <script src="~/AdminPage/bower_components/select2/dist/js/select2.full.min.js"></script>
    <!-- babakhani datepicker -->
    <script src="~/AdminPage/dist/js/persian-date-0.1.8.min.js"></script>
    <script src="~/AdminPage/dist/js/persian-datepicker-0.4.5.min.js"></script>
    <!-- CK Editor -->
    <script src="~/AdminPage/bower_components/ckeditor/ckeditor.js"></script>
    <script src="~/AdminPage/bower_components/ckeditor/adapters/jquery.js"></script>




    <script>
        $(function () {
            $('#my-textarea').ckeditor();
        });
    </script>



    <script>
        $(document).ready(function () {


            $('#tarikh').persianDatepicker({
                altField: '#tarikhAlt',
                altFormat: 'X',
                //format: 'D MMMM YYYY HH:mm a',
                format: 'L',
                observer: true,
                timePicker: {
                    enabled: true
                },
            });


            $('.select2').select2();





        });
    </script>

    <script>
        $(document).ready(function () {
            
            

        });
    </script>




}

EndPoint.Site/Areas/Admin/Views/Adding/CreatePageGroup.cshtml
@{
    ViewData["Title"] = "CreatePageGroup";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}


@model Domain.News.PageGroup

@section Csss{

}


<div class="box box-primary">
    <div class="box-header with-border">
        <h3 class="box-title">مثال ساده</h3>
    </div>
    <!-- /.box-header -->
    <!-- form start -->
    <form role="form" asp-action="CreatePageGroup" asp-controller="Adding" method="post" >
        <div class="box-body">
            <div class="form-group">
                <label for="">عنوان</label>
                <input type="text" class="form-control" name="GroupTitle" id="" placeholder="عنوان گروه خبری">
            </div>

       
        </div>
        <!-- /.box-body -->

        <div class="box-footer">
            <button type="submit" class="btn btn-primary btn-block">ارسال</button>
        </div>
    </form>
</div>


<div class="row">
    <div class="col-xs-12">
        <div class="box">
            <div class="box-header">
                <h3 class="box-title">عنوان های موجود</h3>

                @*<div class="box-tools">
                    <div class="input-group input-group-sm" style="width: 150px;">
                        <input type="text" name="table_search" class="form-control pull-right" placeholder="جستجو">

                        <div class="input-group-btn">
                            <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                        </div>
                    </div>
                </div>*@
            </div>
            <!-- /.box-header -->
            <div class="box-body table-responsive no-padding">
                <table class="table table-hover">
                    <tbody>
                        <tr>
                            <th>شماره</th>
                            <th>عنوان</th>

                        </tr>

                        @{

                            foreach (var i in ViewBag.groups)
                            {
                                <tr>
                                    <td >@i.PageGroupId</td>
                                    <td>@i.GroupTitle</td>

                                </tr>
                            }

                        }
                 

                    </tbody>
                </table>
            </div>
            <!-- /.box-body -->
        </div>
        <!-- /.box -->
    </div>
</div>

@section Scripts{

}

EndPoint.Site/Areas/Admin/Views/Adding/EditePage.cshtml
@model EndPoint.Site.Areas.Admin.Models.PageModelView
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@{
    ViewData["Title"] = "CreatePage";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

@section Csss{
    <link rel="stylesheet" href="~/AdminPage/bower_components/select2/dist/css/select2.min.css">
    <!-- babakhani datepicker -->
    <link rel="stylesheet" href="~/AdminPage/dist/css/persian-datepicker-0.4.5.min.css" />

}


<div class="box box-primary">
    <div class="box-header with-border">
        <h3 class="box-title">مثال ساده</h3>
    </div>
    <!-- /.box-header -->
    <!-- form start -->
    <form role="form" enctype="multipart/form-data" asp-action="EditePage" asp-controller="Adding" method="post">
        <div class="box-body">


            <div class="form-group">
                <label>معمولی</label>
                <select class="form-control select2" asp-for="PageGroup" name="PageGroup" style="width: 100%;">
                    @{
                        int s = 0;
                        foreach (var i in ViewBag.groups)
                        {
                            if (s == 0)
                            {
                                <option selected="selected">@i.GroupTitle</option>
                            }
                            else
                            {
                                <option>@i.GroupTitle</option>

                            }
                            s++;
                        }

                    }
                </select>
            </div>

            <div class="form-group">
                <label>انتخاب تاریخ شمسی با خروجی تایم استمپ </label>
                <div class="input-group date">
                    <div class="input-group-addon">
                        <i class="fa fa-calendar"></i>
                    </div>
                    <input type="text" id="tarikh" class="form-control pull-right">
                    <input type="text" asp-for="CreateDate" name="CreateDate" id="tarikhAlt" class="form-control pull-right hidden" >
                </div>
                <!-- /.input group -->
                <br>
            </div>

            <div class="form-group  ">
                <label for="exampleInputEmail1">عنوان</label>
                <input type="text" asp-for="PageTitle" name="PageTitle" class="form-control" id="PageTitle" placeholder="عنوان">
            </div>

            <div class="form-group ">
                <label>توضیح کوتاه</label>
                <textarea class="form-control" asp-for="ShortDescription" id="ShortDescription" name="ShortDescription" rows="3" placeholder="توضیح کوتاه"></textarea>
            </div>


            <div class="form-group">
                @*<textarea class="form-control" name="Text" rows="3" placeholder="متن"></textarea>*@
                <textarea id="my-textarea" asp-for="Text" name="Text"></textarea>
            </div>

            <div class="form-group">
                <label for="exampleInputFile">ارسال فایل</label>
                @{
                    if (Model.Image2 != null)
                    {
                        <img src="@Model.Image2" alt="Alternate Text" />
                    }
                }
                <input type="file" name="Image" id="exampleInputFile">
                <input type="text" name="Image2" class="hidden" value="@Model.Image2">


                <p class="help-block">متن راهنما</p>
            </div>

            <div class="form-group">
                <label for="exampleInputFile">کلمات کلیدی</label>
                <input type="text" asp-for="Tags" name="Tags" class="form-control" id="exampleInputEmail1" placeholder="کلمات کلیدی">
            </div>


            <div class="checkbox">
                <label>
                    <input type="checkbox"> مرا به خاطر بسپار
                </label>
            </div>
        </div>
        <!-- /.box-body -->

        <div class="box-footer">
            <button type="submit" class="btn btn-primary">ارسال</button>
        </div>
    </form>
</div>




@section Scripts{


    <script src="~/AdminPage/bower_components/select2/dist/js/select2.full.min.js"></script>
    <!-- babakhani datepicker -->
    <script src="~/AdminPage/dist/js/persian-date-0.1.8.min.js"></script>
    <script src="~/AdminPage/dist/js/persian-datepicker-0.4.5.min.js"></script>
    <!-- CK Editor -->
    <script src="~/AdminPage/bower_components/ckeditor/ckeditor.js"></script>
    <script src="~/AdminPage/bower_components/ckeditor/adapters/jquery.js"></script>




    <script>
        $(function () {
            $('#my-textarea').ckeditor();
        });
    </script>



    <script>
        $(document).ready(function () {


            $('#tarikh').persianDatepicker({
                altField: '#tarikhAlt',
                altFormat: 'X',
                //format: 'D MMMM YYYY HH:mm a',
                format: 'L',
                observer: true,
                timePicker: {
                    enabled: true
                },
            });


            $('.select2').select2();





        });
    </script>

    <script>
        $(document).ready(function () {
            
            

        });
    </script>




}

EndPoint.Site/Areas/Admin/Views/Adding/ShowPages.cshtml
@{
    ViewData["Title"] = "ShowPages";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml";
}

@model IEnumerable<EndPoint.Site.Areas.Admin.Models.PageModelView>
@*@model IEnumerable<Domain.News.Page>*@

@section Csss{
    <link rel="stylesheet" href="~/AdminPage/bower_components/datatables.net-bs/css/dataTables.bootstrap.min.css">
    <style>
        img {
            height: 50px;
            width: 50px;
        }
    </style>


}




<section class="content">
    <div class="row">
        <div class="col-xs-12">

            <div class="box">
                <div class="box-header">
                    <h3 class="box-title">جدول داده مثال ۲</h3>
                </div>
                <!-- /.box-header -->
                <div class="box-body">
                    <table id="example1" class="table table-bordered table-striped">


                        <thead>
                            <tr>
                                <th>عکس</th>
                                <th width="100px">گروه</th>
                                <th width="100px">عنوان</th>
                                <th>توضیح کوتاه</th>
                                <th width="120px">امکانات</th>
                            </tr>
                        </thead>


                        <tbody>


                            @{
                                foreach (var i in Model)
                                {
                                    <tr>
                                        <td>
                                            <img src=" @i.Image2" alt="Alternate Text" />
                                        </td>
                                        <td>@i.PageGroup</td>
                                        <td>@i.PageTitle</td>
                                        <td>@i.ShortDescription</td>
                                        <td>
                                            <div class="btn-group">
                                                <a class="btn btn-info btn-flat" href="~/Page/GetPage?id=@i.id">
                                                    <i class="fa fa-info"></i>
                                                </a>
                                                <a class="btn btn-warning btn-flat" href="~/Admin/Adding/EditePage/@i.id">
                                                    <i class="fa fa-edit"></i>
                                                </a>
                                                <a class="btn btn-danger btn-flat" href="https://www.zoomg.ir/cinema-news/">
                                                    <i class="fa fa-trash"></i>
                                                </a>
                                                @*<button type="button" class="btn btn-danger btn-flat" data-toggle="modal" data-target="#modal-danger"><i class="fa fa-trash"></i></button>*@
                                            </div>
                                        </td>
                                    </tr>
                                }
                            }



                        </tbody>


                        <tfoot>
                            <tr>
                                <th>عکس</th>
                                <th>گروه</th>
                                <th>عنوان</th>
                                <th>توضیح کوتاه</th>
                                <th>امکانات</th>
                            </tr>
                        </tfoot>

                    </table>
                </div>
                <!-- /.box-body -->
            </div>
            <!-- /.box -->
        </div>
        <!-- /.col -->
    </div>
    <!-- /.row -->
</section>



<div class="modal modal-info fade" id="modal-info">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title">مشخصات</h4>
            </div>
            <div class="modal-body">
                <p>محتوا</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-outline pull-left" data-dismiss="modal">خروج</button>
                <button type="button" class="btn btn-outline">ذخیره</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>
<!-- /.modal -->

<div class="modal modal-warning fade" id="modal-warning">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title">ویرایش</h4>
            </div>
            <div class="modal-body" id="EditeModal">
                <p>محتوا</p>
                @*@await Component.InvokeAsync("EditePage")*@
                <div class="box box-primary">
                    <form role="form" enctype="multipart/form-data" asp-action="CreatePage" asp-controller="Adding" method="post">
                        <div class="box-body">


                            <div class="form-group">
                                <label>معمولی</label>
                                <select class="form-control select2" name="PageGroup" style="width: 100%;">
                                    @{
                                        int s = 0;
                                        foreach (var i in ViewBag.groups)
                                        {
                                            if (s == 0)
                                            {
                                                <option selected="selected">@i.GroupTitle</option>
                                            }
                                            else
                                            {
                                                <option>@i.GroupTitle</option>

                                            }
                                            s++;
                                        }

                                    }
                                </select>
                            </div>

                            <div class="form-group">
                                <label>انتخاب تاریخ شمسی با خروجی تایم استمپ </label>
                                <div class="input-group date">
                                    <div class="input-group-addon">
                                        <i class="fa fa-calendar"></i>
                                    </div>
                                    <input type="text" id="tarikh" class="form-control pull-right">
                                    <input type="text" name="CreateDate" id="tarikhAlt" class="form-control pull-right" hidden>
                                </div>
                                <!-- /.input group -->
                                <br>
                            </div>

                            <div class="form-group  ">
                                <label for="exampleInputEmail1">عنوان</label>
                                <input type="text" name="PageTitle" class="form-control" id="exampleInputEmail1" placeholder="عنوان">
                            </div>

                            <div class="form-group ">
                                <label>توضیح کوتاه</label>
                                <textarea class="form-control" name="ShortDescription" rows="3" placeholder="توضیح کوتاه"></textarea>
                            </div>


                            <div class="form-group">
                                @*<textarea class="form-control" name="Text" rows="3" placeholder="متن"></textarea>*@
                                <textarea id="my-textarea" name="Text"></textarea>
                            </div>

                            <div class="form-group">
                                <label for="exampleInputFile">ارسال فایل</label>
                                <input type="file" name="Image" id="exampleInputFile">

                                <p class="help-block">متن راهنما</p>
                            </div>

                            <div class="form-group">
                                <label for="exampleInputFile">کلمات کلیدی</label>
                                <input type="text" name="Tags" class="form-control" id="exampleInputEmail1" placeholder="کلمات کلیدی">
                            </div>


                            <div class="checkbox">
                                <label>
                                    <input type="checkbox"> مرا به خاطر بسپار
                                </label>
                            </div>
                        </div>
                        <!-- /.box-body -->

                        <div class="box-footer">
                            <button type="submit" class="btn btn-primary">ارسال</button>
                        </div>
                    </form>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-outline pull-left" data-dismiss="modal">خروج</button>
                <button type="button" class="btn btn-outline">ذخیره</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>



<div class="modal modal-danger fade" id="modal-danger">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title">حذف</h4>
            </div>
            <div class="modal-body">
                <p>محتوا</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-outline pull-left" data-dismiss="modal">خروج</button>
                <button type="button" class="btn btn-outline">ذخیره</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div>












@section Scripts{

    <!-- DataTables -->
    <script src="~/AdminPage/bower_components/datatables.net/js/jquery.dataTables.min.js"></script>
    <script src="~/AdminPage/bower_components/datatables.net-bs/js/dataTables.bootstrap.min.js"></script>
    <script>
        $(function () {
            $('#example1').DataTable()

        })
    </script>





    @*<script>
            $(document).ready(function () {
                $("button.btn-warning").click(function () {
                    $.ajax({
                        url: "/Admin/Adding/EditePage",
                        method: "get",
                        data: { id: $(this).attr('id') }

                    }).done(function (data) {
                        $("#EditeModal").html(data)
                    });

                })
            });
        </script>*@

}