EndPoint.Site/Areas/Admin2/Controllers/Home2Controller.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EndPoint.Site.Areas.Admin.Models;
using Application;
using Microsoft.AspNetCore.Hosting;
using Domain.News;
using EndPoint.Site.Extention;

namespace EndPoint.Site.Areas.Admin2.Controllers
{
    [Area("Admin2")]
    public class Home2Controller : Controller
    {
        private UnitOfWork _context;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public Home2Controller(IWebHostEnvironment hostEnvironment)
        {
            _context = new UnitOfWork();
            _webHostEnvironment = hostEnvironment;

        }

        [HttpGet]
        public IActionResult Index()
        {
            var pages = _context.Page.getAll("PageGroup").Select(s => new PageModelView
            {
                id = s.PageId,
                Image2 = s.Image,
                PageTitle = s.PageTitle,
                ShortDescription = s.ShortDescription,
                PageGroup = s.PageGroup.GroupTitle
            });
            ViewBag.groups = _context.PageGroup.getAll();
            return View(pages);
        }


        [HttpGet]
        public IActionResult LoadCreatePageModal()
        {
            ViewBag.groups = _context.PageGroup.getAll();
            var p = new PageModelView();
            p.id = -1;
            return PartialView("_CreatePageModalPartialView", p);
        }

        [HttpPost]
        public IActionResult SubmitCreatePageModal(PageModelView page)
        {
            if (ModelState.IsValid)
            {
                Page p = new Page
                {
                    PageGroupId = _context.PageGroup.findByName(page.PageGroup),
                    PageTitle = page.PageTitle,
                    Text = page.Text,
                    Visit = 0,
                    ShortDescription = page.ShortDescription,
                    Tags = page.Tags,
                    CreateDate = page.CreateDate.toMiladi(),
                    Image = page.Image.SaveImage(_webHostEnvironment.WebRootPath, "\\News\\")
                };



                _context.Page.insert(p);
                _context.Page.save();

                return new JsonResult(new { status = "Success" });
            }


            return new JsonResult(new { status = "Error" });
        }

        [HttpGet]
        public IActionResult LoadEditePageModal(int PageId)
        {
            ViewBag.groups = _context.PageGroup.getAll();
            var p = _context.Page.getByID(PageId);
            var page = new PageModelView
            {
                id = p.PageId,
                PageTitle = p.PageTitle,
                ShortDescription = p.ShortDescription,
                Text = p.Text,
                Tags = p.Tags,
                PageGroup = _context.PageGroup.getByID(p.PageGroupId).GroupTitle,
                CreateDate=p.CreateDate.toShamsi(),
                Image2 = p.Image
            };
            return PartialView("_EditePageModalPartialView", page);
        }
        [HttpPost]
        public IActionResult SubmitEditePageModal(PageModelView page)
        {
            if (ModelState.IsValid)
            {
                var p = _context.Page.getByID(page.id);

                p.PageGroupId = _context.PageGroup.findByName(page.PageGroup);
                p.PageTitle = page.PageTitle;
                p.Text = page.Text;
                p.ShortDescription = page.ShortDescription;
                p.Tags = page.Tags;
                p.CreateDate = page.CreateDate.toMiladi();
                if(page.Image!=null)
                     p.Image = page.Image.SaveImage(_webHostEnvironment.WebRootPath, "\\News\\");

                _context.Page.update(p);
                _context.Page.save();

                return new JsonResult(new { status = "Success" });
            }


            return new JsonResult(new { status = "Error" });
        }

        [HttpPost]
        public IActionResult DeletePage(int PageId)
        {
            if (ModelState.IsValid)
            {

                _context.Page.delete(PageId);
                _context.Page.save();

                return new JsonResult(new { status = "Success" });
            }


            return new JsonResult(new { status = "Error" });
        }



    }
}

EndPoint.Site/Areas/Admin2/Views/Shared/_CreatePageModalPartialView.cshtml
@model EndPoint.Site.Areas.Admin.Models.PageModelView
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers






<form enctype="multipart/form-data" asp-action="SubmitCreatePageModal" asp-controller="Home2" method="post"
      id="CreatePageForm" data-ajax="true" data-ajax-begin="StartLoading()"
      data-ajax-success="CreatePageFormSubmited">

    <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">New message</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
    </div>



    <div class="modal-body">
        <!--Groups-->
        <div class="form-group">
            <label class="control-label">انتخاب گروه</label>
            <select class="form-select" aria-label="Default select example" asp-for="PageGroup" name="PageGroup">
                @{
                    int s = 0;
                    foreach (var i in ViewBag.groups)
                    {
                        if (s == 0)
                        {
                            <option selected="selected">@i.GroupTitle</option>
                        }
                        else
                        {
                            <option>@i.GroupTitle</option>

                        }
                        s++;
                    }

                }
            </select>
        </div>

        <!--date-->
        <div class="form-group">
            <label class="control-label">انتخاب تاریخ </label>
            <input id="cleander" asp-for="CreateDate" name="CreateDate" autocomplete="off" />
            @*<input type="text" id="cleander" />*@
            <span class="text-danger" asp-validation-for="CreateDate"></span>

        </div>

        <!--PageTitle-->
        <div class="form-group">
            <label class="control-label">عنوان</label>
            <input type="text" asp-for="PageTitle" name="PageTitle" class="form-control" id="PageTitle" placeholder="عنوان">
            <span class="text-danger" asp-validation-for="PageTitle"></span>
        </div>

        <!--ShortDescription-->
        <div class="form-group ">
            <label class="control-label">توضیح کوتاه</label>
            <textarea class="form-control" asp-for="ShortDescription" id="ShortDescription" name="ShortDescription" rows="2" placeholder="توضیح کوتاه"></textarea>
            <span class="text-danger" asp-validation-for="ShortDescription"></span>
        </div>

        <!--Text-->
        <div class="form-group ">
            <label class="control-label">متن</label>
            <textarea class="form-control" asp-for="Text" id="ShortDescription" name="Text" rows="4" placeholder="متن"></textarea>
            <span class="text-danger" asp-validation-for="Text"></span>
        </div>

        <!--file-->
        <div class="form-group mt-1">
            <label class="control-label" for="exampleInputFile">ارسال فایل</label>
            @{
                if (Model.Image2 != null)
                {
                    <img src="@Model.Image2" alt="Alternate Text" />
                }
            }
            <input type="file" asp-for="Image" name="Image" id="exampleInputFile">
            <span class="text-danger" asp-validation-for="Image"></span>

        </div>

        <!--Tags-->
        <div class="form-group">
            <label class="control-label" for="exampleInputFile">کلمات کلیدی</label>
            <input type="text" asp-for="Tags" name="Tags" class="form-control" placeholder="کلمات کلیدی">
            <span class="text-danger" asp-validation-for="Tags"></span>
        </div>


    </div>



    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Create</button>

    </div>
</form>

EndPoint.Site/Areas/Admin2/Views/Shared/_EditePageModalPartialView.cshtml
@model EndPoint.Site.Areas.Admin.Models.PageModelView
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers






<form enctype="multipart/form-data" asp-action="SubmitEditePageModal" asp-controller="Home2" method="post"
      id="CreatePageForm" data-ajax="true" data-ajax-begin="StartLoading()"
      data-ajax-success="CreatePageFormSubmited">

    <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">New message</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
    </div>



    <div class="modal-body">
        <!--Groups-->
        <div class="form-group">
            <label class="control-label">انتخاب گروه</label>
            <select class="form-select" aria-label="Default select example" asp-for="PageGroup" name="PageGroup">
                @{
                    int s = 0;
                    foreach (var i in ViewBag.groups)
                    {
                        if (s == 0)
                        {
                            <option selected="selected">@i.GroupTitle</option>
                        }
                        else
                        {
                            <option>@i.GroupTitle</option>

                        }
                        s++;
                    }

                }
            </select>
        </div>

        <!--date-->
        <div class="form-group">
            <label class="control-label">انتخاب تاریخ </label>
            <input id="cleander" asp-for="CreateDate" name="CreateDate" autocomplete="off" />
            @*<input type="text" id="cleander" />*@
            <span class="text-danger" asp-validation-for="CreateDate"></span>

        </div>

        <!--PageTitle-->
        <div class="form-group">
            <label class="control-label">عنوان</label>
            <input type="text" asp-for="PageTitle" name="PageTitle" class="form-control" id="PageTitle" placeholder="عنوان">
            <span class="text-danger" asp-validation-for="PageTitle"></span>
        </div>

        <!--ShortDescription-->
        <div class="form-group ">
            <label class="control-label">توضیح کوتاه</label>
            <textarea class="form-control" asp-for="ShortDescription" id="ShortDescription" name="ShortDescription" rows="2" placeholder="توضیح کوتاه"></textarea>
            <span class="text-danger" asp-validation-for="ShortDescription"></span>
        </div>

        <!--Text-->
        <div class="form-group ">
            <label class="control-label">متن</label>
            <textarea class="form-control" asp-for="Text" id="ShortDescription" name="Text" rows="4" placeholder="متن"></textarea>
            <span class="text-danger" asp-validation-for="Text"></span>
        </div>

        <!--file-->
        <div class="form-group mt-1">
            <label class="control-label" for="exampleInputFile">ارسال فایل</label>
            @{
                if (Model.Image2 != null)
                {
                    <img src="@Model.Image2" alt="Alternate Text" />
                    <input type="file" asp-for="Image" name="Image" id="exampleInputFile" />
                }
                else
                {
                    <input type="file" asp-for="Image" name="Image" id="exampleInputFile" required />
                    <span class="text-danger" asp-validation-for="Image"></span>

                }
            }

        </div>

        <!--Tags-->
        <div class="form-group">
            <label class="control-label" for="exampleInputFile">کلمات کلیدی</label>
            <input type="text" asp-for="Tags" name="Tags" class="form-control" placeholder="کلمات کلیدی">
            <span class="text-danger" asp-validation-for="Tags"></span>
        </div>

        <input type="text" asp-for="id" name="id" />
    </div>



    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Edite</button>

    </div>
</form>

EndPoint.Site/Areas/Admin2/Views/Shared/_LayoutAdmin.cshtml
@using EndPoint.Site.Extention;

<!DOCTYPE html>

<html lang="ar" dir="rtl">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <link href="~/MyBootstrap/5.0.2/css/bootstrap.rtl.css" rel="stylesheet" />
    <link href="~/WaitMe/waitMe.css" rel="stylesheet" />
    @await RenderSectionAsync("Csss", required: false)

</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="#">Navbar</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="#">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">Link</a>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Dropdown
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a class="dropdown-item" href="#">Action</a></li>
                            <li><a class="dropdown-item" href="#">Another action</a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" href="#">Something else here</a></li>
                        </ul>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
                    </li>
                </ul>
                <form class="d-flex">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
            </div>
        </div>
    </nav>



    <div>
        @RenderBody()
    </div>



    <script src="~/js/JavaScript.js"></script>
    <script src="~/MyBootstrap/5.0.2/js/bootstrap.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script src="~/WaitMe/waitMe.js"></script>


    @*ajax validate and submit*@
    <script src="https://cdn.jsdelivr.net/npm/jquery-validation@1.19.5/dist/jquery.validate.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.11/jquery.validate.unobtrusive.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-ajax-unobtrusive/3.2.6/jquery.unobtrusive-ajax.js"></script>
    @*ajax validate and submit*@


    <script src="~/js/site.js"></script>



    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>